version: '3.8'

services:
  # Backend API with Socket.IO
  backend:
    build: ./back
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Frontend React App
  frontend:
    build: ./front
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app-network
    environment:
      - BACKEND_URL=http://backend:3001

networks:
  app-network:
    driver: bridge